language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t ehutchllew/docker-ci -f Dockerfile.dev .
script:
  - docker run -e CI=true ehutchllew/docker-ci yarn run test
