language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t ehutchllew/docker-ci -f Dockerfile.dev .
script:
  - docker run -e CI=true ehutchllew/docker-ci yarn run test
deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-ci"
  env: "docker-ci-env"
  bucket: "elasticbeanstalk-us-east-1-201394012156"
  bucket_path: "docker-ci"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  edge: true
