version: '3'
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    stdin_open: true # -i in docker run
    tty: true # -t in docker run
    ports:
      - "4001:3000"
    volumes:
      - /app/node_modules
      - .:/app
